### ISSUE TITLE
Tracking progress in browser is ineffective

### ISSUE THREAD

**Issue by bragle** [thekevinscott/UpscalerJS#1118]
**Describe the bug**
When using the upscaler in a browser, the UI freezes until the process is complete at 100%. This prevents any DOM repaints during the upscaling, rendering the progress tracking ineffective in the browser environment.

**To Reproduce**
1. Visit the [monitoring progress documentation](https://upscalerjs.com/documentation/guides/browser/usage/progress).
2. Click on the "upscale" button provided in the example.
3. Observe that the browser becomes unresponsive and no progress updates are visible until the operation is complete.

**Expected behavior**
The browser should continually be able to repaint the DOM, allowing for the progress to be effectively visible in real-time.

**Additional context**
A potential solution to prevent freezing might be the use of `setTimeout(..., 0)`, enabling the browser to repaint. However, this approach may be perceived as a non-ideal hack. While workarounds exist (using a web worker for example), it would be beneficial if the package provided a more seamless way to handle this for browser environments.

If I can make it work properly, I'm planning to use this package for https://devina.io/image-upscaler instead of my own 3 year old implementation as this looks well maintained and a little more thought through than what I've made 😸

**Comment by thekevinscott** [comment]
Thanks for reporting this. I'm also seeing the progress example not updating. However, I believe that's a bug in the progress example itself, not in the upscaler code. For example, in the demo (https://upscaler.com/demo) you should see live feedback:

![2023-09-10 17 02 52](https://github.com/thekevinscott/UpscalerJS/assets/151596/16b0b679-5f59-409d-8030-2c0635eac33e)

> A potential solution to prevent freezing might be the use of setTimeout(..., 0), enabling the browser to repaint.

[This option is available as `awaitNextFrame`](https://upscalerjs.com/documentation/api/execute#parameters). This will call [`await tf.nextFrame()`](https://github.com/thekevinscott/UpscalerJS/blob/main/packages/upscalerjs/src/makeTick.ts#L10) on every loop during iteration. (`tf.nextFrame` sits on top of `requestAnimationFrame` I believe, so is a bit more robust than `setTimeout`).

I don't advertise this option because I've found it not to be super helpful for good UI performance, particularly next to other approaches such as [patch sizes](https://upscalerjs.com/documentation/guides/browser/performance/patch-sizes/), [warming up models](https://upscalerjs.com/documentation/guides/browser/performance/warmup/), and [web workers](https://upscalerjs.com/documentation/guides/browser/performance/webworker/), but if it helps you I'd love to hear about it.

I'll work on updating the progress example to fix whatever bug is preventing it from updating during progress.

**Comment by bragle** [comment]
Cool! I've switched to UpscalerJS on https://devina.io/image-upscaler now if you'd like to take a look. Stole some of the code from your demo, as I'm sure you can tell 🐱

I ended up using a worker, but I still had to enable `awaitNextFrame` in order to be able to abort the process. Without `awaitNextFrame`, it would finish upscaling before handling the abort message.


Let me know if you'd like me to change or add anything to the attribution!

**Comment by thekevinscott** [comment]
Really cool stuff! Dig the website and love the integration.

> I ended up using a worker, but I still had to enable awaitNextFrame in order to be able to abort the process. Without awaitNextFrame, it would finish upscaling before handling the abort message.

Ah, interesting - I will look into this, that sounds like another bug.

One thing I noticed, for larger images it looks like it's stretching them to fill, though when I toggle the original it looks like it's fine.

<img width="717" alt="Screenshot 2023-10-02 at 7 16 31 PM" src="https://github.com/thekevinscott/UpscalerJS/assets/151596/328534af-4ec4-4299-9388-f9f0ff6921bb">
