### ISSUE TITLE
Unable to run examples

### ISSUE THREAD

**Issue by thomasuster** [thekevinscott/UpscalerJS#274]
1. git clone https://github.com/thekevinscott/UpscalerJS.git
2. cd UpscalerJS/examples/basic/
3. yarn start

Expected: Should start the project in the browser.
Result: Errors with this message.

<img width="816" alt="image" src="https://user-images.githubusercontent.com/220965/162846845-edf55d05-45be-4aa7-8cbb-9f8be559bc28.png">

**Comment by thekevinscott** [comment]
The specific error shown here is because you have to install dependencies first. However, there's a _separate_ bug related to examples that you'd probably hit immediately after, that I've just fixed in #278.

Follow these steps:

1. `git clone https://github.com/thekevinscott/UpscalerJS.git`
2. `cd UpscalerJS`
3. `yarn` _(this is the step that installs dependencies)_
4. `cd examples/basic`
5. `yarn start`

That should get the example working locally. [You can also run the example on CodeSandbox](https://githubbox.com/thekevinscott/upscalerjs/tree/main/examples/basic) which takes care of installing dependencies automatically.

----

Just to be fully transparent, when you run the examples locally, it builds UpscalerJS from local source. The "installing dependencies" step (`yarn`) _also_ builds the Upscaler src (defined in the root `package.json`'s `postinstall` step). 

This means that, for instance, if you `cd`'ed into the examples directory and installed dependencies from there, the `postinstall` step would _not_ be called and you'd get a cryptic error. (You could fix this by explicitly building the upscaler, with `yarn workspace upscaler build`.)

If you run the example on CodeSandbox, it instead refers to the hosted `upscaler` package on NPM.


Let me know if you're still having issues. I'll also make a note to update the docs to be more clear.
