### ISSUE TITLE
Any way to deblur the image only

### ISSUE THREAD

**Issue by Ana0112** [thekevinscott/UpscalerJS#444]
I dont want to 2x or 4x the image, but only deblur/sharpen it.
Is there anyway I can basically select resolution as 1x and still get a sharpened image?
Thanks!

**Comment by thekevinscott** [comment]
Short answer: no.

Longer answer: yes, but you'll need to train your own machine learning model.

This library is built to be model agnostic, meaning [you can provide any model](https://upscalerjs.com/#constructor) that accepts an image-like input (in the form of a 4D tensor) and outputs an image-like input (in the form of a 4D tensor).

The models that exist today are all focused on super resolution. They are all a flavor of ESRGAN, [for which there is a paper here](https://arxiv.org/abs/1809.00219) (that's not to say UpscalerJS only works with ESRGAN, just that it's the only model I've gotten around to converting over).

What you'd want to do is find a model architecture suitable for this domain and transfer it to Tensorflow.js. [I discuss some strategies I used to discover ESRGAN in this blog post I wrote](https://thekevinscott.com/super-resolution-with-js/#hearing-it-through-the-grapevine) (there's also a [video if you prefer that](https://www.conf42.com/JavaScript_2020_Kevin_Scott_image_super_resolution)) which may be of interest if you choose to go down this path. Papers with code is still a great website to browse for models - for instance, [this is the page on deblurring](https://paperswithcode.com/task/deblurring). 

One of the tricky things is that, if you are intending to run in the browser, model performance is not necessarily the best way to evaluate models; you also want to consider inference time so that the model can run efficiently in the browser, and to do that you generally need to download and test the models yourself. The other big thing that makes the process easier is to find a model written in Tensorflow, as this will be easier to convert to Tensorflow.js. Most models are written in PyTorch, and while I've heard of successful conversions to Tensorflow.js, I've not done that myself.

A second approach you could try is to use the [ESRGAN model and train it](https://github.com/idealo/image-super-resolution) specifically for this use case. I have no idea how effective this would be, but my gut says it would be reasonably decent. You would need to collect a dataset - say, [the DIV2k one](https://data.vision.ee.ethz.ch/cvl/DIV2K/) - and then have a data prep step that blurs all your training images. And train it at 1x resolution (I haven't tried training a 1x scale model so there may be some edge cases you'd have to debug).

If you don't have a machine learning background or don't have the time or inclination for the above, it's on my long term roadmap to explore additional models besides ESRGAN and deblurring is definitely a good candidate for an additional model. However, I'm not expecting to have the time to do that anytime soon - maybe next year.
